    %load data
    fid = fopen(['./output/output',num2str(fnr),'.dat']); %file handle
    xc = fread(fid,[ny,nx],'double'); %cell x coordinate (m)
    yc = fread(fid,[ny,nx],'double'); %cell y coordinate (m)
    bed = fread(fid,[ny,nx],'double'); %bed elevation (m)
    ice = fread(fid,[ny,nx],'double'); %ice thickness (m)
    bslope = fread(fid,[ny,nx],'double'); %bed slope (-)
    avasite = fread(fid,[ny,nx],'int'); %hydrology flag (ad hoc)
    slidingslope = fread(fid,[ny,nx],'double'); %bed slope in direction of sliding (-)
    ssedi = fread(fid,[ny,nx],'double'); %surface sediment thickness (m) 
    bsedi = fread(fid,[ny,nx],'double'); %basal-ice sediment thickness (m)
    msedi = fread(fid,[ny,nx],'double'); %mid-ice sediment thickness (m)
    snow = fread(fid,[ny,nx],'double'); %CN parameter (ad hoc)
    particles = fread(fid,[ny,nx],'int'); %number of particles in cell
	inparticles = fread(fid,[ny,nx],'int'); %number of particles in cell
    sediment = fread(fid,[ny,nx],'double'); %sediment thickness (m) 
    surfwater = fread(fid,[ny,nx],'double'); %ice pressure normal to bed (m)
    te = fread(fid,[ny,nx],'double'); %effective pressure (m)
    ts = fread(fid,[ny,nx],'double'); %basal shear stress (m)
    sliding = fread(fid,[ny,nx],'double'); %sliding speed (m/y)
    deformation = fread(fid,[ny,nx],'double'); %ice deformation speed (m/y)
    got = fread(fid,[ny,nx],'double'); %square of deviatoric stress (m2)
    bmelt = fread(fid,[ny,nx],'double'); %basal melting rate (m/y)
    quarrying = fread(fid,[ny,nx],'double'); %total quarrying (m)
    accrate = fread(fid,[ny,nx],'double'); %ice accumulation rate (m/y)
    massb = fread(fid,[ny,nx],'double'); %effective mass balance (m/y)
    fluvial = fread(fid,[ny,nx],'double'); %fluvial erosion
    bwater = fread(fid,[ny,nx],'double'); %ad hoc
    subero = fread(fid,[ny,nx],'double'); %total erosion by weathering (m)
    abrasion = fread(fid,[ny,nx],'double'); %total erosion by abrasion (m)
    isostasy = fread(fid,[ny,nx],'double'); %isostatic uplift/subsidence (m)
    periglacial = fread(fid,[ny,nx],'double'); %total erosion by frost scattering (m)
    Ts = fread(fid,[ny,nx],'double'); %surface temperature in cell (C)
    hillslope = fread(fid,[ny,nx],'double'); %total erosion by hillslope processes (m)
    Ta = fread(fid,[ny,nx],'double'); %Atmospheric temperature (C)
    Tb = fread(fid,[ny,nx],'double'); %Basal temperature (C)
    lakewater = fread(fid,[ny,nx],'double'); %Sliding fraction (-)
    icemargin = fread(fid,[ny,nx],'int'); %ice margin flag
    curv = fread(fid,[ny,nx],'double'); %Melt water channel crosssectional area (m2)
    sdeformation = fread(fid,[ny,nx],'double'); %thickness of water sheet (m)
    qw = fread(fid,[ny,nx],'double'); %water discharge (m3/s)
    bQw = fread(fid,[ny,nx],'double'); %longitudinal stress (m)
    water = fread(fid,[ny,nx],'double'); %water input (m)
    surf_sed = fread(fid,[ny,nx],'double'); %water pressure (m)
    SLf = fread(fid,[ny,nx],'double'); %bed contact fraction (-)
    mw = fread(fid,[ny,nx],'double'); %ad hoc
    streamload = fread(fid,[ny,nx],'double'); %ad hoc
    cbs = fread(fid,[ny,nx],'double'); %basal sediment concentration
    Qt = fread(fid,[ny,nx],'double'); %ad hoc
    smelt = fread(fid,[ny,nx],'double'); %ad hoc
    tslope = fread(fid,[ny,nx],'double'); %ad hoc
    hslope = fread(fid,[ny,nx],'double'); %ad hoc
    basal_sed = fread(fid,[ny,nx],'double'); %ad hoc
    theta = fread(fid,[ny,nx],'double'); %ad hoc
    hillslope_erate2 = fread(fid,[ny,nx],'double'); %ad hoc
	landslide = fread(fid,[ny,nx],'double'); %ad hoc
    fnetwork = fread(fid,[ny,nx],'double'); %x velocity (m/y)
    vy_d = fread(fid,[ny,nx],'double'); %y velocity (m/y
    dbdx = fread(fid,[ny,nx+1],'double'); %x velocity residual (m/y)
    dbdy = fread(fid,[ny+1,nx],'double'); %y velocity residual (m/y)
    fclose(fid);